interface Attachment

class Video(val id: Int,
            val ownerId: Int,
            val title:String,
            val description: String,
            val duration:Int,
            val image: Array<String>,
            val firstFrame: Array<String>,
            val date: Int,
            val adding_date: Int,
            val views: Int,
            val comments: Int,
            val player:String,
            val platform: String,
            val canAdd: Boolean,
            val isPrivate:Boolean = true,
            val accessKey: String,
            val processing: Boolean = true,
            val isFavorite: Boolean,
            val canComment: Boolean,
            val canEdit: Boolean,
            val canLike: Boolean,
            val canRepost: Boolean,
            val canSubscribe: Boolean,
            val canAddToFaves: Boolean,
            val canAttachLink: Boolean,
            val width: Int,
            val height: Int,
            val userId: Int,
            val converting: Boolean,
            val added: Boolean,
            val isSubscribed: Boolean,
            val repeat: Int = 1,
            val type: String,
            val balance: Int,
            val liveStatus: String,
            val live: Boolean = true,
            val upcoming: Boolean = true,
            val spectators: Int,
            val likes: Int,
            val reposts: Int) : Attachment
class Audio(val id: Int,
            val ownerId: Int,
            val artist: String,
            val title: String,
            val duration: Int,
            val url: String,
            val lyrics_id: Int = 0,
            val albumId: Int = 0,
            val genreId: Int,
            val date: Int,
            val noSearch: Boolean = true,
            val is_hq: Boolean = true): Attachment
class Photo(val id: Int,
            val albumId: Int,
            val ownerId: Int,
            val userId:Int,
            val text: String,
            val date: Int,
            val sizes: Array<String>,
            val width: Int,
            val height: Int): Attachment
class Doc(val id: Int,
          val ownerId: Int,
          val title: String,
          val size: Int,
          val ext: String,
          val url: String,
          val date: Int,
          val type: Int,
          val preview: Any): Attachment
class Lin(val url: String,
          val title: String,
          val caption: String?,
          val description: String,
          val photo: Any?,
          val product: Any?,
          val button: Any?,
          val previewPage: String,
          val previewUrl: String): Attachment